//+------------------------------------------------------------------+
//| Indicator Test Script Template                                     |
//| Generated by Trade Bot — test_script_generator.py                 |
//|                                                                    |
//| This file is a TEMPLATE. The actual test script is generated       |
//| by test_script_generator.py for your specific strategy.            |
//|                                                                    |
//| HOW TO USE:                                                        |
//| 1. In the EA Generator panel, click "Step 1: Generate Test Script" |
//| 2. Save the generated .mq5 file to: [MT5 data]/MQL5/Scripts/      |
//| 3. Open MetaEditor (F4 in MT5) and compile (F7)                   |
//| 4. Drag the script onto any chart                                   |
//| 5. Open Experts tab (Ctrl+E) — read the OK / FAIL results         |
//| 6. All OK? -> proceed to "Step 2: Generate Full EA"               |
//+------------------------------------------------------------------+
#property script_show_inputs

// {HANDLE_DECLARATIONS}

void OnStart()
{
   int total  = 0;
   int passed = 0;
   int failed = 0;

   Print("=========================================");
   Print("INDICATOR TEST — Starting...");
   Print("Symbol: ", _Symbol);
   Print("=========================================");

   // {TEST_BLOCKS}

   Print("=========================================");
   Print("RESULTS: ", passed, "/", total, " indicators OK");
   if(failed > 0)
      Print("FAIL: Fix the failed indicators before running the EA");
   else
      Print("ALL INDICATORS WORK — safe to compile the full EA");
   Print("=========================================");
}
//+------------------------------------------------------------------+
